services:
  web:
    container_name: web
    image: 585136111625.dkr.ecr.eu-west-1.amazonaws.com/apin-plane-space:latest
    restart: always
    depends_on:
      - api

  admin:
    container_name: admin
    image: 585136111625.dkr.ecr.eu-west-1.amazonaws.com/apin-plane-admin:latest
    restart: always
    depends_on:
      - api
      - web

  space:
    container_name: space
    image: 585136111625.dkr.ecr.eu-west-1.amazonaws.com/apin-plane-space:latest
    restart: always
    depends_on:
      - api
      - web

  api:
    container_name: api
    image: 585136111625.dkr.ecr.eu-west-1.amazonaws.com/apin-plane-api:latest
    restart: always
    env_file:
      - ./apiserver/.env
    depends_on:
      - plane-redis

  worker:
    container_name: bgworker
    image: 585136111625.dkr.ecr.eu-west-1.amazonaws.com/apin-plane-api:latest
    restart: always
    env_file:
      - ./apiserver/.env
    depends_on:
      - api
      - plane-redis

  beat-worker:
    container_name: beatworker
    image: 585136111625.dkr.ecr.eu-west-1.amazonaws.com/apin-plane-api:latest
    restart: always
    env_file:
      - ./apiserver/.env
    depends_on:
      - api
      - plane-redis

  migrator:
    container_name: plane-migrator
    image: 585136111625.dkr.ecr.eu-west-1.amazonaws.com/apin-plane-api:latest
    restart: no
    env_file:
      - ./apiserver/.env
    depends_on:
      - plane-redis

  plane-redis:
    container_name: plane-redis
    image: redis:7.2.4-alpine
    restart: always
    volumes:
      - redisdata:/data

volumes:
  redisdata: