apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-beat
  labels:
    component: beat
    release: {{ .Release.Name }}
spec:
  selector:
    matchLabels:
      component: beat
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        component: beat
        release: {{ .Release.Name }}
    spec:
      {{- if .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml .Values.nodeSelector | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.planeBackend.image.repository }}:{{ .Values.planeBackend.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.planeBackend.image.pullPolicy }}
          command: [ "./bin/beat" ]
          env: 
            {{- range $key, $value := .Values.planeBackend.env }}
            - name: {{ $key | quote}}
              value: {{ $value | quote }}
            {{- end }}
          resources:
            {{ toYaml .Values.planeBeat.resources | indent 12 }}
