version: "3.8"

services:
  web:
    image: ${DOCKERHUB_USER:-local}/plane-frontend:${APP_RELEASE:-latest}
    build:
      context: .
      dockerfile: ./web/Dockerfile.web

  space:
    image: ${DOCKERHUB_USER:-local}/plane-space:${APP_RELEASE:-latest}
    build:
      context: ./
      dockerfile: ./space/Dockerfile.space
      depends_on:
      - web

  admin:
    image: ${DOCKERHUB_USER:-local}/plane-admin:${APP_RELEASE:-latest}
    build:
      context: ./
      dockerfile: ./admin/Dockerfile.admin
      depends_on:
      - space

  api:
    image: ${DOCKERHUB_USER:-local}/plane-backend:${APP_RELEASE:-latest}
    build:
      context: ./apiserver
      dockerfile: ./Dockerfile.api
      depends_on:
      - admin