apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-environment-variables
data:
  {{- range $key, $val := .Values.env }}
  {{- if $val }}
  {{ $key }}: {{ $val | quote }}
  {{- end }}
  {{- end }}

