
name: Docker Branch Build

on:
  workflow_dispatch

env:
  gh_branch: ${{ github.ref_name }}
  img_tag: latest

jobs:
  branch_build_and_push:
    name: Build and Push Web/Space/API/Proxy Docker Image
    runs-on: ubuntu-20.04

    steps:
      - name: Check out the repo
        uses: actions/checkout@v3.3.0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2.5.0

      - name: Login to Docker Hub
        uses: docker/login-action@v2.1.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}


      - uses: ASzc/change-string-case-action@v2
        id: gh_branch_upper_lower
        with:
          string: ${{ env.gh_branch }}

      - uses: mad9000/actions-find-and-replace-string@2
        id: gh_branch_replace_slash
        with:
          source: ${{ steps.gh_branch_upper_lower.outputs.lowercase }}
          find: '/'        
          replace: '-'

      - uses: mad9000/actions-find-and-replace-string@2
        id: gh_branch_replace_dot
        with:
          source: ${{ steps.gh_branch_replace_slash.outputs.value }}
          find: '.'        
          replace: ''
          
      - uses: mad9000/actions-find-and-replace-string@2
        id: gh_branch_clean
        with:
          source: ${{ steps.gh_branch_replace_dot.outputs.value }}
          find: '_'
          replace: ''


      - name: Build and Push Frontend to Docker Container Registry
        uses: docker/build-push-action@v4.0.0
        with:
          context: .
          file: ./web/Dockerfile.web
          platforms: linux/amd64
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/plane-frontend-${{ steps.gh_branch_clean.outputs.value }}:${{ env.img_tag }}
          push: true
        env:
          DOCKER_BUILDKIT: 1
          DOCKER_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          DOCKET_PASSWORD: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push Plane-Deploy to Docker Hub
        uses: docker/build-push-action@v4.0.0
        with:
          context: .
          file: ./space/Dockerfile.space
          platforms: linux/amd64
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/plane-space-${{ steps.gh_branch_clean.outputs.value }}:${{ env.img_tag }}
          push: true
        env:
          DOCKER_BUILDKIT: 1
          DOCKER_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          DOCKET_PASSWORD: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push Backend to Docker Hub
        uses: docker/build-push-action@v4.0.0
        with:
          context: ./apiserver
          file: ./apiserver/Dockerfile.api
          platforms: linux/amd64
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/plane-backend-${{ steps.gh_branch_clean.outputs.value }}:${{ env.img_tag }}
        env:
          DOCKER_BUILDKIT: 1
          DOCKER_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          DOCKET_PASSWORD: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push Plane-Proxy to Docker Hub
        uses: docker/build-push-action@v4.0.0
        with:
          context: ./nginx
          file: ./nginx/Dockerfile
          platforms: linux/amd64
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/plane-proxy-${{ steps.gh_branch_clean.outputs.value }}:${{ env.img_tag }}
          push: true
        env:
          DOCKER_BUILDKIT: 1
          DOCKER_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          DOCKET_PASSWORD: ${{ secrets.DOCKERHUB_TOKEN }}
