name: Build and Push Backend Docker Image

on:
  push:
    branches:
      - 'develop'
    tags:
      - '*.*.*'

jobs:
  build_push_backend:
    name: Build and Push Api Server Docker Image
    runs-on: ubuntu-20.04

    steps:
      - name: Check out the repo
        uses: actions/checkout@v3.3.0

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2.1.0
        with:
          platforms: linux/arm64,linux/amd64

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2.5.0

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2.1.0
        with:
          registry: "ghcr.io"
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Login to Docker Hub
        uses: docker/login-action@v2.1.0
        with:
          registry: "registry.hub.docker.com"
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Extract metadata (tags, labels) for Docker (Docker Hub) Develop
        id: ghmeta
        uses: docker/metadata-action@v4.3.0
        with:
          images: makeplane/plane-backend
          flavor: |
            latest=false
          tags: |
            type=semver,pattern={{version}}

      - name: Extract metadata (tags, labels) for Docker (Github)
        id: dkrmeta
        uses: docker/metadata-action@v4.3.0
        with:
          images: ghcr.io/${{ github.repository }}-backend
          flavor: |
            latest=false
          tags: |
            type=ref,event=tag

      - name: Build and Push to GitHub Container Registry Develop
        if: startsWith(github.ref, 'refs/heads/develop')
        uses: docker/build-push-action@v4.0.0
        with:
          context: ./apiserver
          file: ./apiserver/Dockerfile.api
          platforms: linux/arm64,linux/amd64
          push: true
          cache-from: type=gha
          cache-to: type=gha
          tags: makeplane/plane-backend:develop
          labels: ${{ steps.ghmeta.outputs.labels }}

      - name: Build and Push to Docker Hub
        id: build-and-push-image-develop
        if: startsWith(github.ref, 'refs/heads/develop')
        uses: docker/build-push-action@v4.0.0
        with:
          context: ./apiserver
          file: ./apiserver/Dockerfile.api
          platforms: linux/arm64,linux/amd64
          push: true
          cache-from: type=gha
          cache-to: type=gha
          tags: makeplane/plane-backend:develop
          labels: ${{ steps.dkrmeta.outputs.labels }}

      - name: Build and Push to GitHub Container Registry Tag 
        if: startsWith(github.ref, 'refs/tags/')
        uses: docker/build-push-action@v4.0.0
        with:
          context: ./apiserver
          file: ./apiserver/Dockerfile.api
          platforms: linux/arm64,linux/amd64
          push: true
          cache-from: type=gha
          cache-to: type=gha
          tags: ${{ steps.ghmeta.outputs.tags }}
          labels: ${{ steps.ghmeta.outputs.labels }}

      - name: Build and Push to Docker Hub
        id: build-and-push-image-tag
        if: startsWith(github.ref, 'refs/tags/')
        uses: docker/build-push-action@v4.0.0
        with:
          context: ./apiserver
          file: ./apiserver/Dockerfile.api
          platforms: linux/arm64,linux/amd64
          push: true
          cache-from: type=gha
          cache-to: type=gha
          tags: ${{ steps.dkrmeta.outputs.tags }}
          labels: ${{ steps.dkrmeta.outputs.labels }}